// auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SINGUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// navigation
export const NAVIGATE_TO_HOME_PAGE = 'NAVIGATE_TO_HOME_PAGE'
export const RECEIVED_ALL_ITEM = 'RECEIVED_ALL_ITEM'
export const FETCH_ALL_REJECTED = 'FETCH_ALL_REJECTED'

export const NAVIGATE_TO_PERSONAL_PAGE = 'NAVIGATE_TO_PERSONAL_PAGE'
export const RECEIVED_USER_INFO = 'RECEIVED_USER_INFO'
export const FETCH_USER_INFO_REJECTED = 'FETCH_USER_INFO_REJECTED'
