// auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SINGUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// navigation
export const NAVIGATE_TO_HOME_PAGE = 'NAVIGATE_TO_HOME_PAGE'
export const RECEIVED_ALL_ITEM = 'RECEIVED_ALL_ITEM'
export const FETCH_ALL_REJECTED = 'FETCH_ALL_REJECTED'

export const NAVIGATE_TO_PERSONAL_PAGE = 'NAVIGATE_TO_PERSONAL_PAGE'
export const RECEIVED_USER_INFO = 'RECEIVED_USER_INFO'
export const FETCH_USER_INFO_REJECTED = 'FETCH_USER_INFO_REJECTED'

export const NAVIGATE_TO_SIGNUP_PAGE = 'NAVIGATE_TO_SIGNUP_PAGE'

// personal page
export const ADD_NEW_POST = 'ADD_NEW_POST'
export const SUBMIT_NEW_POST = 'SUBMIT_NEW_POST'
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS'
export const POST_ITEM_FAILED = 'POST_ITEM_FAILED'
export const CANCEL_POST = 'CANCEL_POST'
export const EDIT_POST = 'EDIT_POST'
